version: '3'

services:
    web:
        image: nginx:latest
        container_name: aplicacao
        ports:
            - "8080:80"
        volumes:
            - ./site:/site
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - site-network
        links:
            - php
    php:
        image: php:fpm
        container_name: php
        volumes:
            - ./site:/site
        networks:
            - site-network

networks:
    site-network:
        driver: bridge