# Autor: CarryOn Tech
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.define:app do |app_config|
        app_config.vm.network "private_network", ip: "192.168.50.10"
        app_config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y puppet"
        app_config.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "app.pp"
        end
        app_config.vm.provider:virtualbox do |v|
            v.memory = 1024
            v.cpus = 1
        end
    end

    config.vm.define:db do |db_config|
        db_config.vm.network "private_network", ip: "192.168.50.11"
        db_config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y puppet"
        db_config.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "db.pp"
        end
        db_config.vm.provider:virtualbox do |v|
            v.memory = 1024
            v.cpus = 1
        end
    end
    
end
