-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 14:05:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_veiculo` (
  `cod_` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `cod_veiculo` INT NOT NULL AUTO_INCREMENT,
  `modelo_veiculo` VARCHAR(45) NULL,
  `cor_veiculo` VARCHAR(45) NULL,
  `ano_fab` VARCHAR(45) NULL,
  `preco_veiculo` VARCHAR(45) NULL,
  `fabricante` VARCHAR(45) NULL,
  `Tipo_veiculo_cod_` INT NOT NULL,
  PRIMARY KEY (`cod_veiculo`, `Tipo_veiculo_cod_`),
  INDEX `fk_Veiculo_Tipo_veiculo_idx` (`Tipo_veiculo_cod_` ASC),
  CONSTRAINT `fk_Veiculo_Tipo_veiculo`
    FOREIGN KEY (`Tipo_veiculo_cod_`)
    REFERENCES `mydb`.`Tipo_veiculo` (`cod_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `cod_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(45) NULL,
  `ultimonome` VARCHAR(45) NULL,
  `cpf` VARCHAR(15) NULL,
  `rg` VARCHAR(15) NULL,
  `datanasc` VARCHAR(10) NULL,
  `idade` INT(3) NULL,
  `endereco` VARCHAR(250) NULL,
  `login` VARCHAR(20) NULL,
  `senha` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`cod_user`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
